# Generated by Django 3.1.6 on 2021-05-05 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_reservation_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supply',
            name='drop_of_before',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='failities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supply',
            name='features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supply',
            name='houserules',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supply',
            name='pick_up_from',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
